CUAPB/urls.py
from django.conf.urls import include, url
from django.contrib import admin


from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse

from django.conf import settings
from django.conf.urls.static import static

from police_archive import views





urlpatterns = [
    url(r'^admin/backup/', views.backup),
    url(r'^$', lambda r: HttpResponseRedirect('police_archive/')),
	url(r'^police_archive/', include('police_archive.urls')),
	url(r'^admin/', admin.site.urls),
	url(r'^tinymce/', include('tinymce.urls')),
  
  
]
if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

police_archive/urls.py
from django.conf.urls import url
from django.conf.urls import handler404
from django.conf import settings
from . import views
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
	url(r'^$', views.search, name='index'),
	# url(r'^(?P<question_id>[0-9]+)/$', views.detail, name='detail'),
	url(r'^results/$', views.results, name='results'),
	url(r'^complaint_results/$', views.complaint_results, name='complaint_results'),
	url(r'^officer/(?P<officer_id>\d+)/', views.officer, name='officer'),
	url(r'^complaint/(?P<incident_id>[0-9-]+)/', views.incident, name='incident'),
	url(r'^browse/(?P<letter>\w)/', views.browse, name='browse'),


	


    # url(r'^officer/(?P<officer_badge>\d+)/', views.officer, name='officer'),
    # url(r'^incident/(?P<case_number>\w+\-\w+)/', views.incident, name='incident'),
] 

police_archive/models.py
from __future__ import unicode_literals

from django.db import models
from tinymce import models as tinymce_models





class Officer(models.Model):
	first_name = models.CharField(max_length=80, blank=True, null=True)
	last_name = models.CharField(max_length=80, blank=True, null=True)
	badge = models.IntegerField(blank=True, null=True)
	department = models.CharField(max_length=50, blank=True, null=True)
	model_pic = models.ImageField(upload_to = "police_archive/officer_photos", default= 'noimage', blank=True, null=True)
	description = tinymce_models.HTMLField(blank=True, null=True)

	def __str__(self):
		return self.last_name + ', ' + self.first_name

	class Meta():
		ordering = ['last_name']
		unique_together = ["first_name","last_name","badge", "department"]

	 



class Incident(models.Model):
	officer = models.ManyToManyField(Officer, through='Details')
	case_number = models.CharField(max_length=50, blank=True)
	department = models.CharField(max_length=50, blank=True, null=True)

	OFFICE_CHOICES = (
	('CRA', 'Civilian Review Authority'),
	('IA', 'Internal Affairs'),
	('OPCR', 'Office of Police Conduct Review'),
	('POST', 'Post Board')
	)
	office = models.CharField(max_length=10,
	choices=OFFICE_CHOICES,
	)

	def __str__(self):
		return self.case_number

	class Meta():
		ordering = ['-case_number']
		unique_together = ["case_number", "department"]

class Details(models.Model):
	officer = models.ForeignKey(Officer, on_delete=models.CASCADE, blank=True)
	incident = models.ForeignKey(Incident, on_delete=models.CASCADE, blank=True)
	allegation = models.CharField(max_length=50, blank=True)
	finding = models.CharField(max_length=50, blank=True)
	action = models.CharField(max_length=50, blank=True)


	def __str__(self):
			return self.officer.first_name + ' '+ self.officer.last_name+ ', ' + self.incident.case_number

	class Meta():
		verbose_name_plural = "details"
		ordering = ['incident__case_number']


class SiteText(models.Model):
	content1 = tinymce_models.HTMLField()
	content2 = models.TextField(max_length=500, blank=True)

police_archive/forms.py
from django import forms
from police_archive.models import Officer, SiteText
from tinymce.widgets import TinyMCE

class SearchForm(forms.Form):
    text = forms.CharField(label='Name or Badge Number', max_length=100)
    department_list=Officer.objects.all().values_list('department', flat='true')
    department_list = list(set(department_list))  # deduplicates
    department_list = filter(None, department_list)
    for value in department_list:
    	if Officer.objects.all().filter(department=value)==0:
    		department_list.remove(value)
    
    choices=[('','')]
    for item in department_list :
    	choices.append((item,item))
    department=forms.ChoiceField(choices, label='Department', required=False)

class ComplaintSearchForm(forms.Form):
	input = forms.CharField(label='Case Number', max_length=100)


class AdminTextForm(forms.ModelForm):

    content1 = forms.CharField(widget=TinyMCE(attrs={'cols': 10, 'rows': 30}))
    content2= forms.CharField(widget=TinyMCE(attrs={'cols': 50, 'rows': 30}))

    class Meta:
        model = SiteText
        fields= '__all__'

class OfficerTextForm(forms.ModelForm):
    description = forms.CharField(widget=TinyMCE(attrs={'cols': 50, 'rows': 30}), required=False)

    class Meta:
        model = SiteText
        fields= '__all__'

police_archive/views.py
from django.shortcuts import render, render_to_response
from django.http import HttpResponseRedirect, HttpResponse
from django.db.models import Q
from police_archive.models import Officer, Incident, Details, SiteText
from string import ascii_uppercase
from django.template import RequestContext
from police_archive.forms import SearchForm, ComplaintSearchForm
from django.core.management import call_command

def search(request):
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = SearchForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            # ...
            # redirect to a new URL:
            return HttpResponseRedirect('/thanks/')

    # if a GET (or any other method) we'll create a blank form
    else:
        form = SearchForm()

      # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        complaint_form = ComplaintSearchForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            # ...
            # redirect to a new URL:
            return HttpResponseRedirect('/thanks/')

    # if a GET (or any other method) we'll create a blank form
    else:
        complaint_form = ComplaintSearchForm()

    text = SiteText.objects.get(id=1)

    return render(request, 'police_archive/search.html', {
        'SiteText':text, 'form': form, 'complaint_form': complaint_form, 'alphabet':ascii_uppercase, 'class_name':'home'})

def results(request):
	text = request.GET.get('text', 'default')
	department = request.GET.get('department', 'default')

	try:
		int(text)
		badge=text
	except:
		badge=999999999999   #if text is not a number, make badge number irrelevant


	search_results=Officer.objects.all().filter(
    Q(first_name__icontains=text) | Q(last_name__icontains=text) | Q(badge=badge), Q(department__icontains=department)
)
	search_results = search_results.order_by('last_name')
	return render(request, 'police_archive/results.html', {
        'text':text,'department':department, 'search_results':search_results, 'class_name':'results'})

def complaint_results(request):
	input = request.GET.get('input', 'default')
	search_results=Incident.objects.all().filter(case_number=input)
	return render(request, 'police_archive/complaint_results.html', {
        'search_results':search_results, 'class_name':'complaint_results'})

def officer(request, officer_id):
	officer_id = int(officer_id)
	officer = Officer.objects.get(id=officer_id)
	details_list= officer.details_set.all()
	incident_list=[]
	for details in details_list :
		incident_list.append(details.incident)

	return render(request, 'police_archive/officer.html', {
        'officer':officer,'details_list':details_list, "incident_list":incident_list, 'class_name':'officer'})

def incident(request, incident_id):
	incident=Incident.objects.all().get(case_number=incident_id)
	officer_list = incident.officer.all()
	officer_list = officer_list.order_by('last_name')
	details_list = Details.objects.filter(incident=incident)
	return render(request, 'police_archive/incident.html', {
        'incident':incident, 'officer_list':officer_list, 'details_list':details_list, 'class_name':'incident'})

def browse(request, letter):
	officer_list = Officer.objects.filter(last_name__startswith=letter)
	officer_list = officer_list.order_by('last_name')
	return render(request, 'police_archive/browse.html', {
        'officer_list':officer_list,'class_name':'browse', 'alphabet':ascii_uppercase})

def backup(request):
    return HttpResponse('Backup Made')

police_archive/templates/police_archive/base.html
<!DOCTYPE html>
<html>
<head lang="en">
	{% load staticfiles %}
    <meta charset="UTF-8">
    <title>{% block title %}Page{% endblock %}</title>
    <link href='https://fonts.googleapis.com/css?family=Oswald' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Droid+Sans' rel='stylesheet' type='text/css'>
   <link rel="stylesheet" type="text/css" href="{% static 'police_archive/css/style.css' %}"/>
   <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
    
</head>

<body>
  <div id= 'container' class='{{class_name}}'>

  <div id='content'>
    {% block content %}{% endblock %}
  
  </div>

  <footer>
    <div class='back-to-main'>
      {{current_page.is_home}}<p> <a id='back-to-search' href='/police_archive'> &larr; Back to Search </a></p><p> <a href='http://www.cuapb.org'> &larr; Back to CUAPB main site </a></p>
    </div>
    <div class='top-strip'>
    </div>
  	<a href=''>
  		<div class='donate-strip'>
  			<p><a href='http://www.cuapb.org/donate'> If you are able, please donate to allow this project to continue developing </a></p>
  		</div>
  	</a>
  	<div class='credits'>
  		<p> Archive by <a href='http://www.bigriverwebdesign.com'>Big River Web Design </a>&bull; Powered by <a href='https://www.djangoproject.com/'> Django </a> </p>
  </footer>

  </div>
</body>
</html>

police_archive/templates/police_archive/browse.html
{% extends 'police_archive/base.html' %}

{% block content %}
	<h2 class='page_title'>Results</h2>
	<div class='text-box'>
	    
	    {% if officer_list %}
		    <ul>
		    {% for officer in officer_list %}
		       <a href='/police_archive/officer/{{officer.id}}'> <li>{{officer.last_name}}, {{officer.first_name}}. #{{officer.badge}}. {{officer.department}}.</li> </a>
		    {% endfor %}
		    </ul>
		{% else %}
			No Results Found.
		{% endif %}
	</div>


	<div class='browse'>
		<ul class='letters'>
			{% for c in alphabet %}
				<li><a href='/police_archive/browse/{{c}}'>{{c}}</a></li>
			{% endfor %}
		</ul>
	</div>


{% endblock %}

police_archive/templates/police_archive/complaint_results.html
{% extends 'police_archive/base.html' %}

{% block content %}
	<h2 class='page_title'>Complaint Search  Results</h2>
	<div class='results text-box'>
	    
	    {% if search_results %}
		    <ul>
		    {% for incident in search_results %}
		       <a href='/police_archive/complaint/{{incident.case_number}}'> <li>{{incident.case_number}} </a>, {{incident.get_office_display}}</li>
		    {% endfor %}
		    </ul>
		{% else %}
			No Results Found.
		{% endif %}
	</div>
{% endblock %}

police_archive/templates/police_archive/extrahead.html
{% block extrahead %}

{% endblock %}

police_archive/templates/police_archive/incident.html
{% extends 'police_archive/base.html' %}

{% block content %}
<h2 class='page_title'> Complaint Details </h2>
<div class='text-box'>
	<h2> Complaint #{{incident.case_number}}, {{incident.get_office_display }} </h2>

	<table class='border'>
		<tr>
			<th> Officer </th>
			<th> Allegation </th>
			<th> Finding </th>
			<th> Chief's Action </th>
		</tr>

		{% for details in details_list %}
		<tr>
			<td><a href='/police_archive/officer/{{details.officer.id}}'> {{details.officer.last_name}}, {{details.officer.first_name}} </a></td>
			<td>{{details.allegation}}</td>
			<td>{{details.finding}}</td>
			<td>{{details.action}}</td>
		</tr>
		{% endfor %}
	</table>
</div>

{% endblock %}

police_archive/templates/police_archive/officer.html
{% extends 'police_archive/base.html' %}

{% block content %}
	{% load staticfiles %}

    <h2 class='page_title'> Results </h2>
    <div class='text-box'>    
	    <h2> {{officer.first_name}} {{officer.last_name}}, badge #{{officer.badge}} </h2>
	    <p><strong>Department:</strong> {{officer.department}}</p>
	  
	    {% if officer.model_pic.url != 'media/noimage'%}
	    	<img src='/{{officer.model_pic.url }}'>
	    {% endif %}
	    <p>{{officer.description|safe}}</p>
	    <h2>Complaints</h2>
	    <ul>
	    	{% for details in details_list %}
	    		<li>
	                
	    			
	    			{% if details.incident.case_number %}<a href='/police_archive/complaint/{{details.incident.case_number}}'>{{details.incident.case_number}}</a>{% else %}No Case Number Found{% endif %}{% if details.incident.office %}, {{details.incident.get_office_display}}{% else %}, No office found{% endif %}{% if details.allegation %}, {{details.allegation}}{% endif %}{% if details.finding %}, {{details.finding}}{% endif %}{% if details.action %}, {{details.action}}{% endif %}  
	                       
		    	</li>
	    	{% endfor %}
    </div>


{% endblock %}

police_archive/templates/police_archive/results.html
{% extends 'police_archive/base.html' %}

{% block content %}
	<h2 class='page_title'>Results</h2>
	<div class='results text-box'>
	    
	    {% if search_results %}
		    <ul>
		    {% for officer in search_results %}
		       <a href='/police_archive/officer/{{officer.id}}'> <li>{{officer.last_name}}, {{officer.first_name}}. #{{officer.badge}}. {{officer.department}}.</li> </a>
		    {% endfor %}
		    </ul>
		{% else %}
			No Results Found.  This search platform only will find exact matches of strings. For example, searching "Rusell" will not find Officer Russell.  If you don't know exactly what an officer's name is, try searching just a piece of it.  We also have limited information in the database, so we may not have the officer you're looking for on record.
		{% endif %}
	</div>

{% endblock %}

police_archive/templates/police_archive/search.html
{% extends 'police_archive/base.html' %}

{% block content %}
	<div class='page_title'>
		<h2>{{SiteText.content1|striptags}}</h2>
	</div>

	<div id='search-info' class='text-box'>
   	 <p> {{SiteText.content2|safe}}</p>
   	</div>
   	<div class='officer_search_form text-box'>
   		<h2> Search by Officer </h2>
	    <form method="get" action="results">
	        <table>
	            {{ form }}
	            <tr>
	                <td>&nbsp;</td>
	                <td>
	                    <input type="submit" value="Search">
	                </td>
	            </tr>
	        </table>
	    </form>
	</div>

	<div class='officer_search_form text-box'>
   		<h2> Search by Complaint </h2>
	    <form method="get" action="complaint_results">
	        <table>
	            {{ complaint_form }}
	            <tr>
	                <td>&nbsp;</td>
	                <td>
	                    <input type="submit" value="Search">
	                </td>
	            </tr>
	        </table>
	    </form>
	</div>

	<div class='browse text-box'>
		<h2> Browse by Last Name </h2>
		<ul class='letters'>
			{% for c in alphabet %}
				<li><a href='/police_archive/browse/{{c}}'>{{c}}</a></li>
			{% endfor %}
		</ul>
	</div>
{% endblock %}

police_archive/templates/search.html
{% extends 'base.html' %}

{% block content %}
    <h2>Search</h2>

    <form method="get" action=".">
        <table>
            {{ form.as_table }}
            <tr>
                <td>&nbsp;</td>
                <td>
                    <input type="submit" value="Search">
                </td>
            </tr>
        </table>


        {% if query %}
            <p>You searchd for &quot;{{ query }}&quot;</p>
        {% endif %}
        
        {% if query %}
            <h3>Results</h3>

            {% for result in page.object_list %}
                <p>
                    <a href="{{ result.object.get_absolute_url }}">{{ result.object.title }}</a>
                </p>
            {% empty %}
                <p>No results found.</p>
            {% endfor %}

            {% if page.has_previous or page.has_next %}
                <div>
                    {% if page.has_previous %}<a href="?q={{ query }}&amp;page={{ page.previous_page_number }}">{% endif %}&laquo; Previous{% if page.has_previous %}</a>{% endif %}
                    |
                    {% if page.has_next %}<a href="?q={{ query }}&amp;page={{ page.next_page_number }}">{% endif %}Next &raquo;{% if page.has_next %}</a>{% endif %}
                </div>
            {% endif %}
        {% else %}
            {# Show some example queries to run, maybe query syntax, something else? #}
        {% endif %}
    </form>
{% endblock %}

police_archive/templates/search/search.html
{% extends 'base.html' %}

{% block content %}
    <h2>Search</h2>

    <form method="get" action=".">
        <table>
            {{ form.as_table }}
            <tr>
                <td>&nbsp;</td>
                <td>
                    <input type="submit" value="Search">
                </td>
            </tr>
        </table>

        {% if query %}
            <h3>Results</h3>

            {% for result in page.object_list %}
                <p>
                    <a href="{{ result.object.get_absolute_url }}">{{ result.object.title }}</a>
                </p>
            {% empty %}
                <p>No results found.</p>
            {% endfor %}

            {% if page.has_previous or page.has_next %}
                <div>
                    {% if page.has_previous %}<a href="?q={{ query }}&amp;page={{ page.previous_page_number }}">{% endif %}&laquo; Previous{% if page.has_previous %}</a>{% endif %}
                    |
                    {% if page.has_next %}<a href="?q={{ query }}&amp;page={{ page.next_page_number }}">{% endif %}Next &raquo;{% if page.has_next %}</a>{% endif %}
                </div>
            {% endif %}
        {% else %}
            {# Show some example queries to run, maybe query syntax, something else? #}
        {% endif %}
    </form>
{% endblock %}